baseURL = "https://localhost/local-stage/"
[params]
    data_repo = "http://localhost/EHDP-data/"
    data_branch = "feature-new-data-explorer"

[caches]
    [caches.getresource]
        dir = ':cacheDir/:project'
        maxAge = 0

# [server.headers]
#     for = '/**'
#     [server.headers.values]
#         Access-Control-Allow-Origin = "*"