#!/bin/bash

# Get commit hash
commit_hash=$(git log -1 --format=%H)

# Get short version of commit hash (7 characters)
shorthash=$(git rev-parse --short=7 HEAD)

# Get commit time
commit_timestamp=$(git log -1 --format=%ct)

# Parse commit timestamp
commit_timestamp_parsed=$(date -d "$commit_timestamp" "+%Y-%m-%d-%H%M")

# Full git log for reference file
git_log=$(git log -1 --format=fuller)

# Save git log output (no file extension, so won't get served)
echo "$git_log" > "/git_log"

# Save full commit hash
echo -n "$commit_hash" > "/commit_hash.txt"
