#!/bin/bash

has_git=$(git status)

if [[ "$has_git" ]]; then 

    export HUGO_GIT_BRANCH=$(git branch --show-current)
    export HUGO_GIT_LAST_HASH=$(git log -1 --format=%h --abbrev=10)
    export HUGO_GIT_LAST_MSG=$(git log -1 --format=%s)

fi
