baseURL = "https://gcappbesp307.health.dohmh.nycnet/dev-stage/"
[params]
    data_branch = "content-chronic-disease-topic"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = 0