baseURL = "https://gcappbesp307.health.dohmh.nycnet/dev-stage/"
[params]
    data_branch = "feature-new-data-explorer"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = 0