baseURL = "https://gcappbesp307.health.dohmh.nycnet/dev-stage/"
[params]
    data_branch = "feature-pagefind-search"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1