baseURL = "https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/"
[params]
    # sitepath = "/EH-dataportal"
    data_branch = "production"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = 0